fn main() {
    let output = std::process::Command::new("git")
        .args(["rev-parse", "HEAD"])
        .output()
        .expect("Failed to execute git");
    let rev = String::from_utf8(output.stdout).expect("Failed to parse git output");
    println!("cargo:rustc-env=GIT_COMMIT_SHA={rev}");
    println!("cargo:rustc-rerun-if-changed=.git/HEAD");

    generate_x86_signatures();
}

fn generate_x86_signatures() {
    let sig_root = std::path::Path::new("assets/signatures/x86");
    println!("cargo:rerun-if-changed={}", sig_root.display());

    // Collect all *.yml files recursively, sorted for determinism.
    let mut entries: Vec<std::path::PathBuf> = Vec::new();
    collect_yml(sig_root, &mut entries);
    entries.sort();

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = std::path::Path::new(&out_dir).join("x86_signatures_generated.rs");

    let mut code = String::from(
        "/// Auto-generated by build.rs from assets/signatures/x86/**/*.yml\n\
         pub const SIGNATURES_X86: &[(&str, &str)] = &[\n",
    );

    for path in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        // The stem (filename without .yml) becomes the symbol name.
        let stem = path.file_stem().unwrap().to_str().unwrap();
        // Escape backslashes for Windows paths in the include_str! macro.
        let rel = path.to_str().unwrap().replace('\\', "/");
        // include_str! path must be relative to the workspace root (manifest dir).
        // build.rs cwd is the workspace root.
        code.push_str(&format!(
            "    ({stem:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{rel}\"))),\n",
        ));
    }

    code.push_str("];\n");

    std::fs::write(&out_path, code).expect("Failed to write x86_signatures_generated.rs");
}

fn collect_yml(dir: &std::path::Path, out: &mut Vec<std::path::PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_yml(&path, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("yml") {
            out.push(path);
        }
    }
}
